disable ci configuration

diff --git a/.github/workflows/news-file.yml b/.github/workflows/news-file.yml
--- a/.github/workflows/news-file.yml
+++ b/.github/workflows/news-file.yml
@@ -1,25 +1,25 @@
-name: Check
+# name: Check
 
-on:
-  pull_request:
-    types: [labeled, unlabeled, opened, reopened, synchronize]
+# on:
+#   pull_request:
+#     types: [labeled, unlabeled, opened, reopened, synchronize]
 
-jobs:
-  check-news-entry:
-    name: news entry
-    runs-on: ubuntu-20.04
+# jobs:
+#   check-news-entry:
+#     name: news entry
+#     runs-on: ubuntu-20.04
 
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          # `towncrier check` runs `git diff --name-only origin/main...`, which
-          # needs a non-shallow clone.
-          fetch-depth: 0
+#     steps:
+#       - uses: actions/checkout@v3
+#         with:
+#           # `towncrier check` runs `git diff --name-only origin/main...`, which
+#           # needs a non-shallow clone.
+#           fetch-depth: 0
 
-      - name: Check news entry
-        if: "!contains(github.event.pull_request.labels.*.name, 'skip news')"
-        run: |
-          if ! pipx run towncrier check --compare-with origin/${{ github.base_ref }}; then
-            echo "Please see https://pip.pypa.io/dev/news-entry-failure for guidance."
-            false
-          fi
+#       - name: Check news entry
+#         if: "!contains(github.event.pull_request.labels.*.name, 'skip news')"
+#         run: |
+#           if ! pipx run towncrier check --compare-with origin/${{ github.base_ref }}; then
+#             echo "Please see https://pip.pypa.io/dev/news-entry-failure for guidance."
+#             false
+#           fi
